name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: olafurpg/setup-scala@v13
      with:
        java-version: zulu@1.8
    - uses: coursier/cache-action@v6
    - run: |
        wget https://raw.githubusercontent.com/lefou/millw/main/millw && chmod +x millw
        ./millw valinor.compile
        ./millw valinor.assembly
        mv out/valinor/assembly.dest/out.jar valinor.assembly.jar
    - uses: actions/upload-artifact@v3
      with:
        name: assembly
        path: valinor.assembly.jar
