on:
  push:
  schedule:
    - cron: '0 0 * * 0'

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu
    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.10.9
    - name: Launch Scala Steward
      uses: scala-steward-org/scala-steward-action@v2
      with:
        author-email: scala-steward@noreply.github.com
